language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text -c test/ --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
